### ISSUE TITLE
Debugging is always on

### ISSUE THREAD

**Issue by brownoxford** [srikrsna/protoc-gen-gotag#10]
`pgs.Init()` is called with `pgs.DebugMode()`, which always sets debug to be on - this is causing some (minor) issues with tools like `prototool` that expect plugins to be silent on success.

It would be better if `pgs.init()` was called with `pgs.DebugEnv("DEBUG")` or something similar so that debugging is off by default, but could be turned on with an environment variable.

**Comment by srikrsna** [comment]
Thank you for suggesting the improvement.

**Comment by brownoxford** [comment]
Thanks for the quick fix!, was just getting ready to start on a PR :)
