### ISSUE TITLE
add support for the --go_opt=module=module/package_path option

### ISSUE THREAD

**Issue by mscno** [srikrsna/protoc-gen-gotag#15]
Currently if the proto file is located in a go module, and this module is part of the **go_package** option in the protofile, protoc-gen-gotag is not able to parse correctly the filepaths.

## Example

We have a go mod: `my_module`

and then we have proto file:
`rpc/service.proto` with `go_package="my_module/rpc/`

When protoc is run with flag ` --go_opt=module=my_module`, then the module prefix is trimmed away, and the resulting `service.pb.go` file is generated in `rpc/` rather than in the subfolder `my_module/rpc`

It would be great if protoc-gen-gotag would also support and respect the go_opt=module prefix trimmer.

**Comment by focusaurus** [comment]
I would love to see any example of this in the docs. The `protoc` command line is **SO** confusing. I can't tell which exact placement and syntax I need to invoke this functionality correctly.

**Comment by PramodChaitanyakvv** [comment]
yes, can someone provide more detailed examples on this. Appreciate any help, thanks!
