### ISSUE TITLE
Publish python codegen

### ISSUE THREAD

**Issue by sgtsquiggs** [srikrsna/protoc-gen-gotag#24]
Hi,

I'm using gotag but also generating python code. The python codegen expects to be able to import `tagger` as well regardless of if it's actually used...

Currently I'm vendoring `tagger_pb2.py` but an import would be more ideal.

The googleapis python code is published as `googleapis-common-protos` in a somewhat complex way: https://github.com/googleapis/python-api-common-protos

Perhaps we can have a `tagger-protos` py lib? I could probably submit a PR w/ a script to do all the work except the publish step.

**Comment by srikrsna** [comment]
Should we maintain a separate repo for it?

**Comment by srikrsna** [comment]
I can help with buf setup. I'll add a note in the readme for python developers. Let me know what you think.
