### ISSUE TITLE
[Solved] Not working with buf v0.55.0+

### ISSUE THREAD

**Issue by Leanndrosouza** [srikrsna/protoc-gen-gotag#26]
I cloned this project itself to use as example and i used buf v0.56.0. 

When i run `buf generate` command in project root, the following error is returned: `Failure: failed to map insertion points: file "tagger/tagger.pb.go" defined multiple times.`.  

I thought it might be some conflict with the already generated file, so I deleted `tagger/tagger.pb.go` file and tried to regenerate it, and the following error happens: 

```
[error] [gotag]: open tagger/tagger.pb.go: no such file or directory
Failure: failed to generate plugins concurrently: failed to execute plugins concurrently: failed to generate: exit status 1.
```

This happens when buf version v0.55.0+ is used.

**Comment by srikrsna** [comment]
buf is running multiple plugins concurrently in each directory. For this plugin to work it has to be executed after `protoc-gen-go`

**Comment by srikrsna** [comment]
Fixed it in the repo with a temporary solution. Basically creates a separate config file for gotag and run it after regular `buf generate`. Example: `buf generate --template buf.gen.tag.yaml`

**Comment by FlymeDllVa** [comment]
Is there an example with the latest version of buf? I tried buf.build/sri krsna/plugins/go tag:v0.6.2 move to a separate buff templates, but got open *.pb.go: no such file or directory

**Comment by srikrsna** [comment]
@FlymeDllVa 

For the same reasons described in this issue, the `gotag` plugin can't be used for remote generation. I will remove that plugin from BSR. I was just playing around to see how plugins can be pushed to BSR.

**Comment by chandraaditya** [comment]
@srikrsna 

I don't understand why the plugin shouldn't be published, because it would be really really useful for remote plugin execution(https://docs.buf.build/bsr/remote-generation/plugin-example), so would it be possible for you to push this as a plugin?

**Comment by FlymeDllVa** [comment]
I agree, it is not clear how to use a plugin with modern development tools

**Comment by srikrsna** [comment]
@FlymeDllVa @chandraaditya https://github.com/bufbuild/buf/issues/1069#issuecomment-1098207995
