### ISSUE TITLE
The googleapis that protoc-gen-gotag depends on needs to be updated

### ISSUE THREAD

**Issue by vicnoah** [srikrsna/protoc-gen-gotag#36]
The googleapis that protoc-gen-gotag depends on needs to be updated, currently using buf mod update when referencing protoc-gen-gotag will report an error

```
Failure: commit with name "f503ec6637504fc3be424ad20a5a4225" was not found

You may need to upgrade your googleapis/googleapis dependency.
```

**Comment by srikrsna** [comment]
Pushed a new commit: https://buf.build/srikrsna/protoc-gen-gotag/docs/main
