### ISSUE TITLE
what is the future of protoc-gen-gotag?

### ISSUE THREAD

**Issue by archen** [srikrsna/protoc-gen-gotag#45]
Hey @srikrsna, this project has been very helpful. Thank you for your work!

The lack of engagement on Issues and Pull Requests (particularly to keep supporting newer proto features) is making it difficult to justify keeping this library in our dependency tree. I understand if you're too busy to pay attention to this OSS project, but I am curious about your plans for it.

Is it a dead project for you? Would you be willing to select new maintainers? etc.

Really, the project has made the adoption of proto as a means of expressing data objects once throughout the stack a pleasure, and I hate to see it wither. I hope this finds you well, and that you are able to take at least a few minutes to respond.

P.S. in lieu of a response... an official release with this PR merged https://github.com/srikrsna/protoc-gen-gotag/pull/44 would be incredible!

**Comment by srikrsna** [comment]
Yeah sorry about this, if any one wants to maintain it I am happy to add them to the repo or transfer the repo. Regarding #44 I'll get to it over this weekend and create a release. Sorry for the lack of attention.

I was just pondering an alternate design before I cut a v1 for this, I just have to try it out, if not I'd like to rewrite the plugin using the go protobuf's plugin package.

**Comment by Kavuti** [comment]
Hi @srikrsna, 

I would like to help you with the maintenance and evolution of the project. Feel free to contact me to my email address if you would like to talk about it and maybe give me some starting information.

**Comment by srikrsna** [comment]
Hey @Kavuti I added you as a collaborator to the repo, I've also emailed you. Feel free to review, approve and cut releases. Let me know if you any help with permissions. I am also open to transferring the repo if that is needed.

**Comment by archen** [comment]
any traction here?

**Comment by ucpr** [comment]
Hi @srikrsna! Thank you for your great work on the project.

I'm interested in the current status of this issue and would appreciate an update when you have a moment. I've confirmed that @Kavuti has been added as a collaborator. I understand you're very busy, so please let me know if you need any help maintaining the project.

Thanks!

**Comment by srikrsna** [comment]
Hey @ucpr , thank you I could really use the help in maintaining the project. Let me know how you want to be involved

**Comment by ucpr** [comment]
@srikrsna 
Thank you for your quick reply!
I can participate in the development, review, and release as a collaborator, or take over the project entirely 🙆🏼‍♂️

**Comment by ldepaulatrac** [comment]
fell free to add me here too, i use this a lot and will be happy to help whenever i can

**Comment by mesmerx** [comment]
fell free to add me here too, i use this a lot and will be happy to help whenever i can

**Comment by mesmerx** [comment]
also i am trying to figure a way to generate the tags without this second step, like a plugin in buf right now

**Comment by Kavuti** [comment]
Hi,
Sorry for not being responsive, but I didn't accept the @srikrsna invitation in time, so it expired.
I was searching a library to generate Go tags in order to use the go validator library, but some time later I found protovalidate directly integrated in the gRPC ecosystem which allowed me to achieve pretty the same result.

Anyway, I would be available if we would like to start working on this library.
With @ucpr and @mesmerx we would be 3 people, that should be enough to allow maintenance and evolution.

**Comment by srikrsna** [comment]
Invited all three

**Comment by Kavuti** [comment]
@ucpr @mesmerx 
Feel free to contact me to my email so we can plan and coordinate our work.

**Comment by ucpr** [comment]
@srikrsna  Thanks!

@Kavuti @mesmerx
OK! I'll email you later, so we can coordinate our work then.
