### ISSUE TITLE
Troubleshooting Error: 'Package Tagger Does Not Exist' When Generating Java Files from Protos

### ISSUE THREAD

**Issue by ArturDell** [srikrsna/protoc-gen-gotag#47]
I'm currently using a plugin that's proven quite useful. Now, I need to generate Java files from protos, but I've hit a snag. When running the following code:

```
protoc \
    -I $(go list -m -f {{.Dir}} github.com/srikrsna/protoc-gen-gotag) \
    --java_out=${JAVA_OUT} \
    --proto_path=${PROTO_DIR} \
    ${PROTO_DIR}/**/**/*.proto
```
I encounter an error stating `XXX.java:[69,11] package tagger does not exist` 

Do you have any suggestions on how to resolve this?

Thanks!

**Comment by Kavuti** [comment]
Hi,
This library is meant to have the so called Go "struct tags" added during the protobuf code generation.
More on Go struct tags: https://go.dev/wiki/Well-known-struct-tagsf

The library is not meant to work for other languages, like Java, since it solves a specific Go need.
