### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by athxx** [srikrsna/protoc-gen-gotag#52]
I follow the document to execute `example.proto` by this command

```bash
protoc -I. \
           -I=${GOPATH}/src/github.com/grpc-ecosystem/grpc-gateway/ \
           -I=${GOPATH}/src/ \
           -I=${GOPATH}/src/github.com/srikrsna/protoc-gen-gotag/ \
           --gotag_opt=paths=source_relative \
           --gotag_out=xxx="mytag+\"-\"":. 
            ./example/example.proto
```

But I can't find `mytag` in the `example.pb.go` file

**Comment by ucpr** [comment]
Hi @athxx!
To add the tag, you need to run the command after executing the regular protobuf generation command.

Can you please try it?

https://github.com/srikrsna/protoc-gen-gotag?tab=readme-ov-file#addreplace-tags

**Comment by ucpr** [comment]
Since there hasn't been any update, I will close this issue. 
If there is any progress, please feel free to comment here and reopen the issue :)
