### ISSUE TITLE
Please add examples of protoc invocation with go_out and grpc

### ISSUE THREAD

**Issue by tandr** [srikrsna/protoc-gen-gotag#6]
We need some documentation or examples _showing_ how to use this plugin together with GRPC generation for example.
I cannot figure it out, the explanation what should run first and what second is confusing, sorry.

**Comment by srikrsna** [comment]
Generate the normal GRPC service definitions and run this after that as separate command.

The reason for this is there is no way to extend the existing go protoc plugin to include this functionality so the way this plugin works is that it parses the generated plugin code and rewrites it with tags.

**Comment by tandr** [comment]
This is exactly what I am talking about. If you can add your comment and couple lines into readme as an example, it would very, very helpful (IMHO)
