### ISSUE TITLE
xxx fields not ignored if proto file does not contains any (tagger.tags) message options

### ISSUE THREAD

**Issue by vtolstov** [srikrsna/protoc-gen-gotag#7]
```
syntax = "proto3";

package org.ump.grpc;

import "tagger/tagger.proto";
import "validate/validate.proto";

service ExampleService {
  rpc Echo(ExampleEchoReq) returns (ExampleEchoRsp) {

  };
};

message ExampleEchoReq {
  string data = 1;
};

message ExampleEchoRsp {
  string data = 1;
};
```

after processing this file all XXX_ fields ignored not added with command 
protoc --gotag_out=paths=source_relative,xxx="xml+\"-\" xorm+\"-\"":. *.proto

but if i'm add string data = 1 [(tagger.tags) = "json:\"-\""]; all XXX fields are ignored with xorm, json and xml tags

**Comment by vtolstov** [comment]
As i understand Execute method not called by protoc if no tags specified in proto file. How to workaround this?

**Comment by vtolstov** [comment]
As i understand we also need to extend not only field of message, but something more global , so protoc call our plugin.

**Comment by srikrsna** [comment]
The plugin is run irrespective of the import. I've found and fixed the issue in the code. Thanks for reporting.

**Comment by vtolstov** [comment]
thanks!
